### ISSUE TITLE
Create alt

### ISSUE THREAD

**Issue by Mysti-Chan** [Cristicorpus/Arkenstone.API#52]
the route allowing the creation of secondary character does not work. It does not create secondary character but returns a token of the new character as the main character

![image](https://user-images.githubusercontent.com/40337663/226497537-b2d67d37-ef22-4493-8ff6-dc435e0ddf87.png)

this code does not find the character. Returns an exception even though the token is in the request (Authorization: Bearer "token")

**Comment by feonor21** [comment]
la modif est sur preprod 
preprod accessible

**Comment by feonor21** [comment]
la modif est sur preprod 
preprod accessible
