### ISSUE TITLE
Set main

### ISSUE THREAD

**Issue by Mysti-Chan** [Cristicorpus/Arkenstone.API#54]
![image](https://user-images.githubusercontent.com/40337663/227721321-91b48c70-26c8-4fed-9319-37d6437ab9e1.png)
![image](https://user-images.githubusercontent.com/40337663/227721325-d7a2edfa-2993-49bd-bc27-e10b34fa23b9.png)

Quand je call /api/character/setmain j'ai cette erreur.

**Comment by feonor21** [comment]
je viens de tester avec plusieurs compte

je n ai eu aucun soucis et aucune erreur.  réessaye avec la préprod

**Comment by Mysti-Chan** [comment]
Ca fonctionne maintenant je close
