### ISSUE TITLE
Error update buy ticket to prod

### ISSUE THREAD

**Issue by Mysti-Chan** [Cristicorpus/Arkenstone.API#61]
![image](https://github.com/Cristicorpus/Arkenstone.API/assets/40337663/5529789c-d417-4639-be71-95d382410e69)

J'essaye d'update un ticket enfant qui est de type achat en type production. 

Sur l'image tu vois mon objet envoyé a ton API sur l'image du bas l'erreur envoyé en retour.

Je ne change pas la quantité qui est resté la même. La seul chose qui a changé c'est la location de production qui diffère de celle du parent.  J'ai essayé en laissant la même location j'ai la même erreur.

Faut-il absolument que l'objet envoyé soit du type suivant ?

```json
{
  "id": 0,
  "item": {
    "id": 0,
    "Name": ""
  },
  "MEefficiency": 0,
  "quantity": 0,
  "type": 0,
  "location": {
    "id": 0
  },
  "state": 0
}
```

EDIT: après un essai ave le type exact comme ci dessus ca ne fonctionne pas j'ai toujours la même erreur et ce même sur Postman

**Comment by feonor21** [comment]
quand la quantity change pas tu a la meme erreur ? si oui ca viens carrément de mon api xD.

**Comment by Mysti-Chan** [comment]
Oui je ne change pas la quantité ca n'a pas de sens de faire ca. Je veux juste prendre un ticket enfant et le passé d'achat en prod ou vice versa.

Le seul truc que j'ai changé c'est la localisation de production de cette enfant mais même en laissant la même que le parent j'ai cette erreur

**Comment by feonor21** [comment]
je regarde ce soir :) je te redit dans la soirée (US-TIME)

**Comment by feonor21** [comment]
tu es localhost.
y as preprod.
